config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :liquids
  resources :accessories
  resources :vapers
  resources :orders
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vaper.rb
class Vaper < ApplicationRecord
    has_and_belongs_to_many :accessories
    has_and_belongs_to_many :orders
end

app/controllers/vapers_controller.rb
class VapersController < ApplicationController
  before_action :set_vaper, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /vapers or /vapers.json
  def index
    @vapers = Vaper.all
  end

  # GET /vapers/1 or /vapers/1.json
  def show
  end

  # GET /vapers/new
  def new
    @vaper = Vaper.new
  end

  # GET /vapers/1/edit
  def edit
  end

  # POST /vapers or /vapers.json
  def create
    @vaper = Vaper.new(vaper_params)

    respond_to do |format|
      if @vaper.save
        format.html { redirect_to @vaper, notice: "Vaper was successfully created." }
        format.json { render :show, status: :created, location: @vaper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vapers/1 or /vapers/1.json
  def update
    respond_to do |format|
      if @vaper.update(vaper_params)
        format.html { redirect_to @vaper, notice: "Vaper was successfully updated." }
        format.json { render :show, status: :ok, location: @vaper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vapers/1 or /vapers/1.json
  def destroy
    @vaper.destroy
    respond_to do |format|
      format.html { redirect_to vapers_url, notice: "Vaper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vaper
      @vaper = Vaper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vaper_params
      params.require(:vaper).permit(:name, :price, :brand, :waranty_time)
    end
end

app/helpers/vapers_helper.rb
module VapersHelper
end

app/views/vapers/_form.html.erb
<%= form_with(model: vaper) do |form| %>
  <% if vaper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vaper.errors.count, "error") %> prohibited this vaper from being saved:</h2>

      <ul>
        <% vaper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :waranty_time %>
    <%= form.text_field :waranty_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vapers/edit.html.erb
<h1>Editing Vaper</h1>

<%= render 'form', vaper: @vaper %>

<%= link_to 'Show', @vaper %> |
<%= link_to 'Back', vapers_path %>

app/views/vapers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vapers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Brand</th>
      <th>Waranty time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vapers.each do |vaper| %>
      <tr>
        <td><%= vaper.name %></td>
        <td><%= vaper.price %></td>
        <td><%= vaper.brand %></td>
        <td><%= vaper.waranty_time %></td>
        <td><%= link_to 'Show', vaper %></td>
        <% if can? :create, Vaper %>
          <td><%= link_to 'Edit', edit_vaper_path(vaper) %></td>
        <% end %>
        <% if can? :create, Vaper %>
          <td><%= link_to 'Destroy', vaper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Vaper %>
  <%= link_to 'New Vaper', new_vaper_path %>
<% end %>

app/views/vapers/new.html.erb
<h1>New Vaper</h1>

<%= render 'form', vaper: @vaper %>

<%= link_to 'Back', vapers_path %>

app/views/vapers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vaper.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @vaper.price %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @vaper.brand %>
</p>

<p>
  <strong>Waranty time:</strong>
  <%= @vaper.waranty_time %>
</p>

<%= link_to 'Edit', edit_vaper_path(@vaper) %> |
<%= link_to 'Back', vapers_path %>