config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :liquids
  resources :accessories
  resources :vapers
  resources :orders
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/liquid.rb
class Liquid < ApplicationRecord
    has_and_belongs_to_many :orders
end

app/controllers/liquids_controller.rb
class LiquidsController < ApplicationController
  before_action :set_liquid, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /liquids or /liquids.json
  def index
    @liquids = Liquid.all
  end

  # GET /liquids/1 or /liquids/1.json
  def show
  end

  # GET /liquids/new
  def new
    @liquid = Liquid.new
  end

  # GET /liquids/1/edit
  def edit
  end

  # POST /liquids or /liquids.json
  def create
    @liquid = Liquid.new(liquid_params)

    respond_to do |format|
      if @liquid.save
        format.html { redirect_to @liquid, notice: "Liquid was successfully created." }
        format.json { render :show, status: :created, location: @liquid }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @liquid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liquids/1 or /liquids/1.json
  def update
    respond_to do |format|
      if @liquid.update(liquid_params)
        format.html { redirect_to @liquid, notice: "Liquid was successfully updated." }
        format.json { render :show, status: :ok, location: @liquid }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @liquid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liquids/1 or /liquids/1.json
  def destroy
    @liquid.destroy
    respond_to do |format|
      format.html { redirect_to liquids_url, notice: "Liquid was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liquid
      @liquid = Liquid.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def liquid_params
      params.require(:liquid).permit(:name, :price, :strength, :flavor, :size, :brand)
    end
end

app/helpers/liquids_helper.rb
module LiquidsHelper
end

app/views/liquids/_form.html.erb
<%= form_with(model: liquid) do |form| %>
  <% if liquid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(liquid.errors.count, "error") %> prohibited this liquid from being saved:</h2>

      <ul>
        <% liquid.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <%= form.text_field :strength %>
  </div>

  <div class="field">
    <%= form.label :flavor %>
    <%= form.text_field :flavor %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/liquids/edit.html.erb
<h1>Editing Liquid</h1>

<%= render 'form', liquid: @liquid %>

<%= link_to 'Show', @liquid %> |
<%= link_to 'Back', liquids_path %>

app/views/liquids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liquids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Strength</th>
      <th>Flavor</th>
      <th>Size</th>
      <th>Brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @liquids.each do |liquid| %>
      <tr>
        <td><%= liquid.name %></td>
        <td><%= liquid.price %></td>
        <td><%= liquid.strength %></td>
        <td><%= liquid.flavor %></td>
        <td><%= liquid.size %></td>
        <td><%= liquid.brand %></td>
        <td><%= link_to 'Show', liquid %></td>
        <% if can? :update, Liquid %>
          <td><%= link_to 'Edit', edit_liquid_path(liquid) %></td>
        <% end %>
        <% if can? :destroy, Liquid %>
          <td><%= link_to 'Destroy', liquid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Liquid %>
  <%= link_to 'New Liquid', new_liquid_path %>
<% end %>

app/views/liquids/new.html.erb
<h1>New Liquid</h1>

<%= render 'form', liquid: @liquid %>

<%= link_to 'Back', liquids_path %>

app/views/liquids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @liquid.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @liquid.price %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @liquid.strength %>
</p>

<p>
  <strong>Flavor:</strong>
  <%= @liquid.flavor %>
</p>

<p>
  <strong>Size:</strong>
  <%= @liquid.size %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @liquid.brand %>
</p>

<%= link_to 'Edit', edit_liquid_path(@liquid) %> |
<%= link_to 'Back', liquids_path %>