config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :liquids
  resources :accessories
  resources :vapers
  resources :orders
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :accessories
  has_and_belongs_to_many :vapers
  has_and_belongs_to_many :liquids
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /orders or /orders.json
  def index
    if current_user.admin?
      @orders = Order.all
    else
      @orders = current_user.order.all
    end
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @vapers = Vaper.all
    @accessories = Accessory.all
    @liquids = Liquid.all

    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params.merge(open: true, date_opened: DateTime.now, date_closed: nil))
    
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:open, :date_opened, :date_closed, :user_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Open</th>
      <th>Date opened</th>
      <th>Date closed</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.open %></td>
        <td><%= order.date_opened %></td>
        <td><%= order.date_closed %></td>
        <td><%= order.user_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Order %>
  <%= link_to 'New Order', new_order_path %>
<% end %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<table>
  <thead>
    <tr>
      <th>Vaper Name</th>
      <th>Price</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @vapers.each do |vaper| %>
      <tr>
        <td><%= vaper.name %></td>
        <td><%= vaper.price %> USD</td>
        <td><%= link_to 'Show', vaper %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<table>
  <thead>
    <tr>
      <th>Accessory Name</th>
      <th>Price</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @accessories.each do |accessory| %>
      <tr>
        <td><%= accessory.name %></td>
        <td><%= accessory.price %> USD</td>
        <td><%= link_to 'Show', accessory %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<table>
  <thead>
    <tr>
      <th>Liquid Name</th>
      <th>Price</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @liquids.each do |liquid| %>
      <tr>
        <td><%= liquid.name %></td>
        <td><%= liquid.price %> USD</td>
        <td><%= link_to 'Show', liquid %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Open:</strong>
  <%= @order.open %>
</p>

<p>
  <strong>Date opened:</strong>
  <%= @order.date_opened %>
</p>

<p>
  <strong>Date closed:</strong>
  <%= @order.date_closed %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>