config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :liquids
  resources :accessories
  resources :vapers
  resources :orders
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/accessory.rb
class Accessory < ApplicationRecord
    has_and_belongs_to_many :vapers
    has_and_belongs_to_many :orders
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :set_accessory, only: %i[ show edit update destroy ]
  load_and_authorize_resource

  # GET /accessories or /accessories.json
  def index
    @accessories = Accessory.all
  end

  # GET /accessories/1 or /accessories/1.json
  def show
  end

  # GET /accessories/new
  def new
    @accessory = Accessory.new
  end

  # GET /accessories/1/edit
  def edit
  end

  # POST /accessories or /accessories.json
  def create
    @accessory = Accessory.new(accessory_params)

    respond_to do |format|
      if @accessory.save
        format.html { redirect_to @accessory, notice: "Accessory was successfully created." }
        format.json { render :show, status: :created, location: @accessory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accessories/1 or /accessories/1.json
  def update
    respond_to do |format|
      if @accessory.update(accessory_params)
        format.html { redirect_to @accessory, notice: "Accessory was successfully updated." }
        format.json { render :show, status: :ok, location: @accessory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accessories/1 or /accessories/1.json
  def destroy
    @accessory.destroy
    respond_to do |format|
      format.html { redirect_to accessories_url, notice: "Accessory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accessory
      @accessory = Accessory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def accessory_params
      params.require(:accessory).permit(:name, :price)
    end
end

app/helpers/accessories_helper.rb
module AccessoriesHelper
end

app/views/accessories/_form.html.erb
<%= form_with(model: accessory) do |form| %>
  <% if accessory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accessory.errors.count, "error") %> prohibited this accessory from being saved:</h2>

      <ul>
        <% accessory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accessories/edit.html.erb
<h1>Editing Accessory</h1>

<%= render 'form', accessory: @accessory %>

<%= link_to 'Show', @accessory %> |
<%= link_to 'Back', accessories_path %>

app/views/accessories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accessories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accessories.each do |accessory| %>
      <tr>
        <td><%= accessory.name %></td>
        <td><%= accessory.price %></td>
        <td><%= link_to 'Show', accessory %></td>
        <% if can? :update, Accessory %>
          <td><%= link_to 'Edit', edit_accessory_path(accessory) %></td>
        <% end %>
        <% if can? :destroy, Accessory %>
          <td><%= link_to 'Destroy', accessory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Accessory %>
  <%= link_to 'New Accessory', new_accessory_path %>
<% end %>

app/views/accessories/new.html.erb
<h1>New Accessory</h1>

<%= render 'form', accessory: @accessory %>

<%= link_to 'Back', accessories_path %>

app/views/accessories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @accessory.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @accessory.price %>
</p>

<%= link_to 'Edit', edit_accessory_path(@accessory) %> |
<%= link_to 'Back', accessories_path %>